CREATE DATABASE ALIAKSEI_KAZIUKOVICH;
GO

USE ALIAKSEI_KAZIUKOVICH;
GO

CREATE SCHEMA sales;
GO

CREATE TABLE sales.Orders (OrderNum INT NULL);
GO

BACKUP DATABASE ALIAKSEI_KAZIUKOVICH
    TO DISK='ALIAKSEI_KAZIUKOVICH.bak';
GO

USE master;
GO

DROP DATABASE ALIAKSEI_KAZIUKOVICH;
GO

RESTORE DATABASE ALIAKSEI_KAZIUKOVICH
    FROM DISK = 'ALIAKSEI_KAZIUKOVICH.bak'
GO
